/**
 * @file poly.h
 * @brief Common code for working with polynomials.
 *
 * Polynomials are represented as T[] with T being defined in common.h.
 * Helper functions for polynomial operations, including printing, multiplication, random sampling,
 * workspace management, comparison, and NTT transformations.
 *
 * Hardware-Aware: The functions are designed to be efficient and secure, making use of techniques
 * such as SIMD operations, efficient memory management, and optimized algorithms for modular arithmetic
 * to ensure that they can handle larger polynomials and moduli efficiently, which is important for
 * applications in cryptography and other areas where performance is critical.
 */
#ifndef POLY_H
#define POLY_H
#include <stddef.h>
#include <stdint.h>

#include "common.h"

/**
 * @brief Dumps a polynomial to stdout, e.g., "a= 16x^2 + 1x^1".
 * Helper function for poly_print to provide a human-readable representation of the polynomial,
 * which is useful for debugging and visualization.
 *
 * Need to ensure that the coefficients are printed in a clear and consistent format, such as "16x^2 +
 * 1x^1", to facilitate easy reading and understanding of the polynomial structure, especially when
 * dealing with polynomials of higher degree where the number of terms can be large.
 *
 * Hardware-Aware: The function should be implemented to efficiently print the coefficients,
 * especially for large polynomials, by minimizing unnecessary string operations and using
 * efficient formatting techniques.
 *
 * @param polyname name to be printed, e.g, "a" in the example above
 * @param a polynomial
 * @param n number of coefficients
 */
void poly_print(char* polyname, T* a, size_t n);

/**
 * @brief Dumps a polynomial to stdout, e.g., [0,1,16].
 * Helper function for poly_print2 to provide a compact representation of the polynomial coefficients,
 * which is useful for debugging and programmatic parsing.
 *
 * Need to ensure that the coefficients are printed in a clear and consistent format, such as a
 * comma-separated list enclosed in brackets, to facilitate easy reading and parsing of the output.
 *
 * Hardware-Aware: The function should be implemented to efficiently print the coefficients,
 * especially for large polynomials,
 *
 * @param a polynomial
 * @param n number of coefficients
 */
void poly_print2(T* a, size_t n);

/**
 * @brief Performs a schoolbook multiplication computing the full product with 2*n-1 coeffs.
 * Helper function for poly_polymul_ref to perform the naive polynomial multiplication, which serves
 * as a reference implementation for correctness and performance comparisons against optimized versions.
 *
 * Need to ensure that the output array c has enough space to hold 2*n-1 coefficients, and that
 * the multiplication is performed correctly with modulus reduction to ensure that the results
 * are suitable for use in cryptographic applications where modular arithmetic is essential.
 *
 * Hardware-Aware: Uses restrict keyword and tight loops to aid compiler auto-vectorization (SIMD).
 *
 * @param c result polynomial
 * @param a first multiplicand polynomial
 * @param aN number of coefficients in a
 * @param b  second multiplicand polynomial
 * @param bN number of coefficients in b
 * @param q modulus
 */
void poly_polymul_ref(T* restrict c, const T* restrict a, size_t aN, const T* restrict b, size_t bN,
                      T q);

/**
 * @brief Samples a uniformly random polynomial with coefficients in [0, q).
 * Helper function for poly_random to generate random polynomials, which is essential for applications
 * such as key generation in cryptographic schemes or for testing purposes.
 *
 * Need to ensure that the generated coefficients are uniformly distributed in the range [0, q)
 * to maintain the security properties of cryptographic applications and to ensure that the random
 * polynomials are suitable for testing.
 *
 * Hardware-Aware: The function should be implemented to efficiently generate random coefficients,
 * potentially using a secure random byte generator and reducing the generated bytes to the desired
 * range, to minimize overhead and ensure that it can generate random polynomials efficiently, especially
 * when a large number of coefficients are needed.
 *
 * @param a polynomial
 * @param n number of coefficients in polynomial
 * @param q modulus
 */
void poly_random(T* a, size_t n, T q);

/**
 * @brief Provides a portion of the workspace for polynomial computations, returning a pointer
 * to a contiguous block of memory that can hold the specified number of coefficients.
 * Helper function for poly_get_workspace to manage the allocation and reuse of workspace memory, which
 * is essential for efficient polynomial computations that may require temporary storage for intermediate
 * results.
 *
 * Need to ensure that the size parameter is used to manage the workspace correctly, allowing for
 * efficient reuse of memory and preventing memory leaks or fragmentation.
 *
 * Hardware-Aware: The function should be implemented to manage a pre-allocated workspace efficiently,
 * minimizing overhead and ensuring that it can provide memory for polynomial computations without
 * unnecessary allocations, which can improve performance in scenarios where multiple polynomial
 * operations are performed in sequence.
 *
 * @param size number of coefficients (not bytes) needed for the workspace
 * @return T* pointer to the workspace memory that can hold the specified number of coefficients
 */
T* poly_get_workspace(size_t size);

/**
 * @brief Releases a portion of the workspace after use, allowing it to be reused for future
 * computations. Helper function for poly_release_workspace to manage the lifecycle of the workspace,
 * ensuring that memory is released properly after use and can be reused efficiently for subsequent
 * computations.
 *
 * Need to ensure that the size parameter matches the size requested from poly_get_workspace
 * to maintain correct workspace management.
 *
 * Hardware-Aware: Ensure that the size parameter matches the size requested from poly_get_workspace
 * to maintain correct workspace management.
 *
 * @param size size of the workspace portion to release, in number of coefficients (not bytes)
 */
void poly_release_workspace(size_t size);

/**
 * @brief Resets the workspace pointer to the beginning of the workspace,
 * allowing for reuse of the entire workspace.
 */
void poly_reset_workspace(void);

/**
 * @brief Returns the current workspace pointer position as a mark.
 * @return size_t current workspace pointer
 */
size_t poly_workspace_get_mark(void);

/**
 * @brief Restores the workspace pointer to a previously saved mark.
 * @param mark workspace pointer position to restore
 */
void poly_workspace_set_mark(size_t mark);

/**
 * @brief Compares two polynomials mod Q.
 * Helper function for poly_compare to perform coefficient-wise comparison of two polynomials a and b,
 * returning 0 if all coefficients are equal modulo q, and 1 if any coefficient differs.
 *
 * Need to perform modulus reduction during comparison to ensure that polynomials are considered
 * equivalent even if their coefficients differ by multiples of q, which is important in many
 * applications where polynomials are considered equivalent under modular arithmetic.
 *
 * Hardware-Aware: Compare polynomials coefficient-wise with modulus reduction, returning early on
 * mismatch to minimize unnecessary computations. This function is crucial for verifying the correctness
 * of polynomial operations, such as checking if two polynomials are equivalent under a given modulus,
 * which is a common requirement in cryptographic algorithms and other applications involving polynomial
 * arithmetic.
 *
 * The early return on mismatch allows for efficient comparisons, especially when dealing with large
 * polynomials, as it avoids unnecessary computations once a difference is found.
 *
 * @param a first polynomial
 * @param b second polynomial
 * @param n number of coefficients in a and b
 * @param q modulus
 * @return int 0 if coefficients are equal mod q, 1 otherwise
 */
int poly_compare(T* a, T* b, size_t n, T q);

/**
 * @brief Loads a polynomial from a file named "input_config".
 * Searches for a line starting with 'name:' (e.g., "A:").
 *
 * @param name name of the polynomial to load (e.g., "A")
 * @param a pointer to the polynomial array
 * @param n number of coefficients to read
 * @return int 0 on success, 1 on failure
 */
int poly_load(const char* name, T* a, size_t n);

/**
 * @brief Naive implementation of a cyclic NTT.
 * Helper function for polymul_cyclic_ntt_forward_reference to perform the cyclic NTT
 * transformation, which is a critical step in preparing polynomials for multiplication
 * in the NTT domain.
 *
 * Needs an n-th root of unity.
 * Computes antt_i = sum_j=0^n (a_j  root^(ij)) for 0 <= i < n.
 *
 * Hardware-Aware: Precomputes powers of the root to avoid O(n^2 log q) complexity.
 * This implementation serves as a reference for correctness and performance comparisons
 * against optimized versions.
 *
 * @param t output polynomial in NTT domain
 * @param a input polynomial in normal domain
 * @param q modulus
 * @param n number of coefficients in a (and t)
 * @param root n-th root of unity modulo q
 */
void polymul_cyclic_ntt_forward_reference(T* t, const T* a, T q, T n, T root);

/**
 * @brief Naive implementation of an inverse cyclic NTT.
 * Helper function for polymul_cyclic_ntt_inverse_reference to perform the inverse cyclic NTT
 * transformation, which is a critical step in recovering the original polynomial after performing
 * operations in the NTT domain.
 *
 * Needs an n-th root of unity.
 * Computes a_i = 1/n * sum_j=0^n (a_j  root^(-ij)) for 0 <= i < n.
 *
 * Hardware-Aware: Precomputes powers of the root inverse to avoid O(n^2 log q) complexity.
 * This implementation serves as a reference for correctness and performance comparisons
 * against optimized versions.
 *
 * @param t output polynomial in normal domain
 * @param a input polynomial in NTT domain
 * @param q modulus
 * @param n number of coefficients in a (and t)
 * @param root n-th root of unity
 */
void polymul_cyclic_ntt_inverse_reference(T* t, const T* a, T q, T n, T root);

/**
 * @brief Naive implementation of a negacyclic NTT.
 * Helper function for polymul_negacyclic_ntt_forward_reference to perform the negacyclic NTT
 * transformation, which is a critical step in preparing polynomials for multiplication in
 * the negacyclic NTT domain.
 *
 * Needs a 2n-th root of unity.
 * Computes antt_i = sum_j=0^n (a_j  root^(2ij + j)) for 0 <= i < n.
 *
 * Hardware-Aware: Precomputes powers of the root to avoid O(n^2 log q) complexity.
 * This implementation serves as a reference for correctness and performance comparisons
 * against optimized versions.
 *
 * @param t output polynomial in NTT domain
 * @param a input polynomial in normal domain
 * @param q modulus
 * @param n number of coefficients in a (and t)
 * @param root 2n-th root of unity
 */
void polymul_negacyclic_ntt_forward_reference(T* t, const T* a, T q, T n, T root);

/**
 * @brief Naive implementation of an inverse negacyclic NTT.
 *
 * Helper function for polymul_negacyclic_ntt_inverse_reference to perform the inverse negacyclic
 * NTT transformation, which is a critical step in recovering the original polynomial after performing
 * operations in the negacyclic NTT domain.
 *
 * Needs a 2n-th root of unity.
 * Computes a_i = 1/n * root^(-i) * sum_j=0^n (a_j  root^(-2ij)) for 0 <= i < n.
 *
 * Hardware-Aware: Precomputes powers of the root inverse to avoid O(n^2 log q) complexity.
 * This implementation serves as a reference for correctness and performance comparisons
 * against optimized versions.
 *
 * @param t output polynomial in normal domain
 * @param a input polynomial in NTT domain
 * @param q modulus
 * @param n number of coefficients in a (and t)
 * @param root 2n-th root of unity
 */
void polymul_negacyclic_ntt_inverse_reference(T* t, const T* a, T q, T n, T root);

void polymul_karatsuba_recursive(T* restrict c, const T* restrict a, const T* restrict b, size_t n, T q,
                                 size_t threshold);

/**
 * @brief Performs 2-D Winograd-based polynomial multiplication (F(3x3, 3x3)).
 *
 * @param c result polynomial
 * @param a first multiplicand polynomial
 * @param aN number of coefficients in a
 * @param b second multiplicand polynomial
 * @param bN number of coefficients in b
 * @param q modulus
 */
void polymul_winograd(T* c, const T* a, size_t aN, const T* b, size_t bN, T q);

#endif
