/**
 * @file randombytes.h
 * @brief Common code for random byte generation.
 */
#ifndef RANDOMBYTES_H
#define RANDOMBYTES_H
#include <stdint.h>

/* Generate n random bytes and store them in buf. */
#ifdef _WIN32
#include <CRTDEFS.H>
#else
#include <unistd.h>
#endif

/**
 * @brief Generates n random bytes and stores them in buf.
 *
 * Helper function for randombytes that provides a platform-independent interface
 * for generating random bytes, which is essential for cryptographic applications
 * that require randomness, such as key generation or nonce creation.
 * The implementation should use a secure source of randomness provided by the operating system,
 * such as /dev/urandom on Unix-like systems or CryptGenRandom on Windows, to ensure that the
 * generated bytes are suitable for cryptographic use.
 *
 * Hardware-Aware: The function should be implemented to minimize overhead and ensure that it can
 * generate random bytes efficiently, especially when a large number of bytes is requested, by batching
 * system calls or using other techniques to reduce the number of calls to the underlying random byte
 * generator, which can improve performance in scenarios where many random bytes are needed, such as in
 * cryptographic key generation or when generating random polynomials.
 *
 * @param buf buffer to store the random bytes
 * @param n number of random bytes to generate
 * @return int 0 on success, -1 on failure
 */
int randombytes(uint8_t* buf, size_t n);

#endif
